CREATE TABLE IF NOT EXISTS product (
    id SERIAL NOT NULL PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    p_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL
);
